name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: windows-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/ramsoft-inc/RapidResults
            azure-pipeline-name: 'RapidResults-Mono.runtime_terror'
            azure-devops-token: gklqvnpfswyqz4ecsds2z4tycdkjw3rh2a3ijsap3flhdg37bbma
